sudo: required
services:
  - docker
  
before_install:
  - docker build -t sehersonmezsoy/docker-react -f Dockerfile.dev .

script:
  - docker run sehersonmezsoy/docker-react npm run test -- --coverage